#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  9 06:39:48 2019

@author: sawarno
"""

"""
j = job
o = operation
p = process time
m = machine 
r = release date
f(t) = cost function
d = due date
w = weight

i, n = index, number

Job Characteristics
a (alpha)= machine enviroment

b (beta) = job characterisitcs
b1 = preemption (job spliting allowed)
    b1 = pmtn if allowed
    b1 != present if not allowed

    b2 = precidence relationships

g (gamma) = optimality criterion

